import puppeteer from 'puppeteer';
import { prisma } from '../prisma';

export const exportService = {
    async generateProposalPDF(proposalId: number) {
        const proposal = await prisma.proposal.findUnique({
            where: { id: proposalId },
            include: {
                company: true,
                client: true,
                stylePalette: true,
            },
        });

        if (!proposal) {
            throw new Error('Proposal not found');
        }

        // In a real app, you might fetch modular blocks here
        // For now, we'll use a placeholder or the proposal title
        const htmlContent = this.generateHTML(proposal);

        const browser = await puppeteer.launch({
            headless: true,
            args: ['--no-sandbox', '--disable-setuid-sandbox'],
        });

        const page = await browser.newPage();
        await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

        const pdfBuffer = await page.pdf({
            format: 'A4',
            printBackground: true,
            margin: {
                top: '20mm',
                bottom: '20mm',
                left: '15mm',
                right: '15mm',
            },
        });

        await browser.close();
        return pdfBuffer;
    },

    generateHTML(proposal: any) {
        const palette = proposal.stylePalette || {
            primaryColor: '#3B82F6',
            secondaryColor: '#1E293B',
            accentColor: '#F59E0B',
            backgroundColor: '#FFFFFF',
            textColor: '#111827',
            headingColor: '#000000',
            fontFamily: 'Inter, sans-serif',
            headingFont: 'Outfit, sans-serif',
        };

        return `
      <!DOCTYPE html>
      <html>
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Outfit:wght@600;800&display=swap" rel="stylesheet">
        <style>
          :root {
            --primary-color: ${palette.primaryColor};
            --secondary-color: ${palette.secondaryColor};
            --accent-color: ${palette.accentColor};
            --bg-color: ${palette.backgroundColor};
            --text-color: ${palette.textColor};
            --heading-color: ${palette.headingColor};
            --font-family: ${palette.fontFamily};
            --heading-font: ${palette.headingFont};
          }
          body {
            font-family: var(--font-family);
            color: var(--text-color);
            background-color: var(--bg-color);
            line-height: 1.6;
            margin: 0;
            padding: 0;
          }
          h1, h2, h3 {
            font-family: var(--heading-font);
            color: var(--heading-color);
          }
          .title-page {
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            text-align: center;
            page-break-after: always;
          }
          .title-page h1 {
            font-size: 4rem;
            margin-bottom: 1rem;
            color: var(--primary-color);
          }
          .section {
            padding: 2rem 0;
          }
          .page-break {
            page-break-after: always;
          }
          .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 0.8rem;
            color: #999;
          }
        </style>
      </head>
      <body>
        <div class="title-page">
          <h1>${proposal.title}</h1>
          <p>Prepared for: ${proposal.company?.name || 'Valued Client'}</p>
          <p>Contact: ${proposal.client?.firstName} ${proposal.client?.lastName}</p>
          <p>Date: ${new Date().toLocaleDateString()}</p>
        </div>
        
        <div class="section">
          <h2>Project Overview</h2>
          <p>This is a high-fidelity proposal generated by ProPixel.</p>
          <!-- In a real implementation, we would map modular blocks here -->
        </div>

        <div class="page-break"></div>

        <div class="section">
          <h2>Scope of Work</h2>
          <p>Details about the scope would be dynamically inserted here.</p>
        </div>

        <div class="footer">
          Proprietary & Confidential - ProPixel
        </div>
      </body>
      </html>
    `;
    }
};
